image:
  file: docker/gitpod-pandoc.Dockerfile

tasks:
  - command: >
        cd arc42-template
        && git checkout master
        && git pull
        && cd ..
        && sdk selfupdate force
        && sdk install java 17.0.15-tem
        && sdk default java 17.0.15-tem
        && ./gradlew createTemplatesFromGoldenMaster
        && ./gradlew arc42
        && ./gradlew createDistribution
        && echo "please check the results in arc42-template/dist"
        && echo "and if ok, add, commit and push it"
