image:
  file: docker/gitpod-pandoc.Dockerfile

tasks:
  - command: >
        cd arc42-template
        && git checkout master
        && git pull
        && cd ..
        && ./gradlew createTemplatesFromGoldenMaster
        && ./gradlew arc42
        && ./gradlew createDistribution